spring:
  profiles:
    active: dev
  messages:
    basename: messages
    encoding: UTF-8

  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/my-db
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    sql-script-encoding: UTF-8
    hikari:
      maximum-pool-size: 30
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect

server:
  port: 8185

logging:
  file: log/app.log
  pattern:
    console: '%clr(%-5p %d{HH:mm:ss.SSS}) (%F:%L\) - %msg%n'
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p) %c{1}[%M]%L - %msg%n'
  level:
    mzonex.excel.tools: debug